---
title: ""
format: pdf
header-includes:
  - \usepackage[paperwidth=27cm, paperheight=35cm, margin = 0.5cm]{geometry}
---

## Setup

```{r}
rm(list = ls())
options(stringsAsFactors = FALSE)
library(rstan)
library(ggplot2)
rstan_options(auto_write = TRUE)            # Cache compiled Stan programs
options(mc.cores = parallel::detectCores()) # Parallelize chains

wd <- "~/projects/seedsarentreal/analyses/methods"
setwd(wd)
util <- new.env()
source(file.path(wd, "mcmc_analysis_tools_rstan.R"), local=util) 
source(file.path(wd, "mcmc_visualization_tools.R"), local=util) 

kippenberger <- c("#8B174DFF", "#AE2565FF", "#C1447EFF", "#D06C9BFF", "#DA9FB8FF", 
                  "#ADBE7CFF", "#8BA749FF", "#6E8537FF", "#4F5F28FF", "#343D1FFF")
```

## Load and format data

```{r}
raw_data <- read.csv(file.path(wd, 'data',  'ebms', 
                               'Beech_tree-ring_masting_data.csv'))
clim_data <- readRDS(file.path(wd, 'data',  'ebms', 
                               'era5land_sitesextract.rds'))

length(unique(paste0(raw_data$site.ID,raw_data$tree.ID))) # 57 unique trees
length(unique(raw_data$site.ID)) # 7 unique sites
raw_data$uniqueID <- paste0(raw_data$site.ID, "_", raw_data$tree.ID)
raw_data <- na.omit(raw_data[,c('site.ID', 'uniqueID', 'year', 'seeds')])

# Sizes
uniq_tree_ids <- unique(raw_data$uniqueID)
N_trees <- length(uniq_tree_ids)
first_year <- min(raw_data$year)
last_year <- max(raw_data$year)
max_years <- first_year:max(raw_data$year)
N_max_years <- length(max_years)

# Format data into ragged arrays
seed_counts <- c()
years <- c()
prevsummer_temps <-c()
spring_temps <-c()
gdd_lastfrost <-c()
N_years <- c()

idx <- 1
tree_start_idxs <- c()
tree_end_idxs <- c()

for (tid in uniq_tree_ids) {
  
  raw_data_tree <- raw_data[raw_data$uniqueID == tid,]
  
  years_tree <- raw_data_tree$year-first_year+1
  years <- c(years, years_tree)
  
  N_years_tree <- length(years_tree)
  N_years <- c(N_years, N_years_tree)
  
  seed_count_tree <- raw_data_tree$seeds
  seed_counts <- c(seed_counts, seed_count_tree)
  
  # all years, even those unobserved
  prevsummer_temps_tree <- clim_data[clim_data$site.ID == raw_data_tree$site.ID[1] & 
                                       clim_data$year %in% (max_years-1), 
                                     'meantmax_ja'] 
  prevsummer_temps <- c(prevsummer_temps, prevsummer_temps_tree)
  
  # all years, even those unobserved
  spring_temps_tree <- clim_data[clim_data$site.ID == raw_data_tree$site.ID[1] & 
                                   clim_data$year %in% (max_years-1), 
                                 'meantmean_am'] 
  spring_temps <- c(spring_temps, spring_temps_tree)
  
  # all years, even those unobserved, in *10degC
  gdd_lastfrost_tree <- clim_data[clim_data$site.ID == raw_data_tree$site.ID[1] & 
                                    clim_data$year %in% (max_years-1), 
                                  'gdd_b5_tolastfrost']/10 
  gdd_lastfrost <- c(gdd_lastfrost, gdd_lastfrost_tree)
  
  tree_start_idxs <- c(tree_start_idxs, idx)
  idx <- idx + N_years_tree
  tree_end_idxs <- c(tree_end_idxs, idx - 1)
  
}
```

## New data for predictions

```{r}
source(file.path(wd, 'climatic_trends.R'))
years_to_predict <- first_year:2100
trees_per_stand <- 5
unique_stands <- unique(clim_data$site.ID)
newtree_stand_idxs <- rep(which(unique_stands==unique_stands), each = trees_per_stand)
N_newtrees <- length(newtree_stand_idxs)
N_max_newyears <- length(years_to_predict)
first_newyear <- first_year

newyears <- c()
newprevsummer_temps <-c()
newspring_temps <-c()
newgdd_lastfrost <-c()
N_newyears <- c()

idx <- 1
newtree_start_idxs <- c()
newtree_end_idxs <- c()

for (i in 1:N_newtrees) {
  
  newyears_tree <- years_to_predict-first_newyear+1
  newyears <- c(newyears, newyears_tree)
  
  N_newyears_tree <- length(newyears_tree)
  N_newyears <- c(N_newyears, N_newyears_tree)
  
  newprevsummer_temps_tree <- newclim_data[newclim_data$site.ID == unique_stands[newtree_stand_idxs[i]] & newclim_data$year %in% years_to_predict, 'meantmax_ja'] 
  newprevsummer_temps <- c(newprevsummer_temps, newprevsummer_temps_tree)
  
  newspring_temps_tree <- newclim_data[newclim_data$site.ID == unique_stands[newtree_stand_idxs[i]] & newclim_data$year %in% years_to_predict, 'meantmean_am'] 
  newspring_temps <- c(newspring_temps, newspring_temps_tree)
  
  newgdd_lastfrost_tree <- newclim_data[newclim_data$site.ID == unique_stands[newtree_stand_idxs[i]] & newclim_data$year %in% years_to_predict, 'gdd_b5_tolastfrost']/10 
  newgdd_lastfrost <- c(newgdd_lastfrost, newgdd_lastfrost_tree)
  
  newtree_start_idxs <- c(newtree_start_idxs, idx)
  idx <- idx + N_newyears_tree
  newtree_end_idxs <- c(newtree_end_idxs, idx - 1)
  
}
```

## Posterior quantification

```{r}
N <- length(years)
Nnew <- length(newyears)
data <- mget(c('N', 'N_trees', 'N_max_years',
               'N_years', 'tree_start_idxs', 'tree_end_idxs',
               'seed_counts', 'years', 
               'prevsummer_temps', 'spring_temps', 'gdd_lastfrost',
               # for predictions
               'Nnew', 'N_newtrees', 'N_max_newyears', 'newtree_stand_idxs',
               'N_newyears', 'newtree_start_idxs', 'newtree_end_idxs','newyears', 
               'newprevsummer_temps', 'newgdd_lastfrost', 'newspring_temps'
               ))

# Posterior quantification
if(FALSE){
  fit <- stan(file= file.path(wd, "stan", "paper_models", "model2_treelevel_zinb_missing_rescaled_summertempfull_springfrost_springtemp_constrainedslopes_wpred.stan"),
              data=data, seed=5838299, chain = 4, cores = 4,
              warmup=1000, iter=2024, refresh=100)
  saveRDS(fit, file = file.path(wd, 'output', 'fit_15sept2025_fullmodel_constrainedslopes.rds'))
  diagnostics <- util$extract_hmc_diagnostics(fit)
  util$check_all_hmc_diagnostics(diagnostics)
  samples <- util$extract_expectand_vals(fit)
  base_samples <- util$filter_expectands(samples,
                                         c('lambda1', 'theta1', 'psi1',
                                           'lambda20', 'psi2', 
                                           'beta_lambda2_frost', 'beta_lambda2_spring',  
                                           'rho0', 'beta_nm_m', 'beta_m_m',
                                           'tau_nm_m0', 'tau_m_m0'))
  util$check_all_expectand_diagnostics(base_samples)
  
  fit <- stan(file= file.path(wd, "stan", "paper_models", "model2_treelevel_zinb_missing_rescaled_summertemp_springfrost_springtemp_constrainedslopes_wpred.stan"),
              data=data, seed=5838299, chain = 4, cores = 4,
              warmup=1000, iter=2024, refresh=100)
  saveRDS(fit, file = file.path(wd, 'output', 'fit_15sept2025_biologymodel_constrainedslopes.rds'))
  diagnostics <- util$extract_hmc_diagnostics(fit)
  util$check_all_hmc_diagnostics(diagnostics)
  samples <- util$extract_expectand_vals(fit)
  base_samples <- util$filter_expectands(samples,
                                         c('lambda1', 'theta1', 'psi1',
                                           'lambda20', 'psi2', 
                                           'beta_lambda2_frost', 'beta_lambda2_spring', 
                                           'rho0', 'beta_nm_m', 
                                           'tau_nm_m0', 'tau_m_m0'))
  util$check_all_expectand_diagnostics(base_samples)
  
  fit <- stan(file= file.path(wd, "stan", "paper_models", "model2_treelevel_zinb_missing_rescaled_summertemp_springfrost_springtemp_wpred.stan"),
              data=data, seed=5838299, chain = 4, cores = 4,
              warmup=1000, iter=2024, refresh=100)
  saveRDS(fit, file = file.path(wd, 'output', 'fit_15sept2025_biologymodel.rds'))
  diagnostics <- util$extract_hmc_diagnostics(fit)
  util$check_all_hmc_diagnostics(diagnostics)
  samples <- util$extract_expectand_vals(fit)
  base_samples <- util$filter_expectands(samples,
                                         c('lambda1', 'theta1', 'psi1',
                                           'lambda20', 'psi2', 
                                           'beta_lambda2_frost', 'beta_lambda2_spring', 
                                           'rho0', 'beta_nm_m', 
                                           'tau_nm_m0', 'tau_m_m0'))
  util$check_all_expectand_diagnostics(base_samples)
}
{
  fit_full_const <- readRDS(file.path(wd, 'output', 'fit_15sept2025_fullmodel_constrainedslopes.rds'))
  fit_biol_const <- readRDS(file = file.path(wd, 'output', 'fit_15sept2025_biologymodel_constrainedslopes.rds'))
  fit_biol <- readRDS(file = file.path(wd, 'output', 'fit_15sept2025_biologymodel.rds'))
}
```

## Retrodictive check

```{r}
samples <- util$extract_expectand_vals(fit_biol)


# Retrodictive check
observed_idxs <- c()
for (t in 1:data$N_trees){
  idxs <- tree_start_idxs[t]:tree_end_idxs[t]
  observed_idxs_tree <- N_max_years*(t-1)+years[idxs]
  observed_idxs <- c(observed_idxs, observed_idxs_tree)
}
par(mfrow=c(1, 1), mar = c(4,4,2,2))
names <- sapply(observed_idxs, function(n) paste0('seed_counts_pred[',n,']'))
util$plot_hist_quantiles(samples[names], 'seed_counts_pred', 0, 340, 20,
                         baseline_values=data$seed_counts, 
                         xlab="Seed counts")
```


```{r}
#| fig-width: 10
#| fig-height: 10

par(mfrow=c(3, 5), mar = c(4,4,2,2))
for (t in 1:data$N_trees) {
  
  idxs_tree <-(1+N_max_years*(t-1)):(N_max_years*t)
  observed_idxs_tree <- tree_start_idxs[t]:tree_end_idxs[t]
  observed_flags <- years[tree_start_idxs[t]:tree_end_idxs[t]]
  
  names <- sapply(idxs_tree,
                  function(n) paste0('seed_counts_pred[', n, ']'))
  xlab="Year"
  xticklabs=first_year:last_year
  ylab="Seed Counts"
  display_ylim=c(0, 400)
  main=paste("Tree", uniq_tree_ids[t])
  
  # Construct bins
  N <- length(names)
  bin_min <- 0.5
  bin_max <- N + 0.5
  bin_delta <- 1
  breaks <- seq(bin_min, bin_max, bin_delta)
  
  plot_config <- util$configure_bin_plotting(breaks)
  plot_idxs <- plot_config[[1]]
  plot_xs <- plot_config[[2]]
  
  # Construct marginal quantiles
  probs <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
  calc <- function(n) {
    util$ensemble_mcmc_quantile_est(samples[[names[n]]], probs)
  }
  quantiles <- sapply(1:N, calc)
  plot_quantiles <- do.call(cbind, lapply(plot_idxs,
                                          function(n) quantiles[1:9, n]))
  
  delta <- 0.05 * (display_ylim[2] - display_ylim[1])
  display_ylim[1] <- display_ylim[1] - delta
  display_ylim[2] <- display_ylim[2] + delta      
  
  plot(1, type="n", main=main,
       xlim=c(bin_min, bin_max), xlab=xlab, xaxt="n",
       ylim=display_ylim, ylab=ylab)
  axis(1, at=1:N, labels=xticklabs)    
  
  for(n in 1:N){
    
    idplot <- c(n*2-1, n*2)
    polygon(c(plot_xs[idplot], rev(plot_xs[idplot])),
            c(plot_quantiles[1,idplot], rev(plot_quantiles[9,idplot])),
            col = ifelse(n%in%observed_flags, util$c_light, 'grey90'), border = NA)
    polygon(c(plot_xs[idplot], rev(plot_xs[idplot])),
            c(plot_quantiles[2,idplot], rev(plot_quantiles[8,idplot])),
            col = ifelse(n%in%observed_flags, util$c_light_highlight, 'grey80'), border = NA)
    polygon(c(plot_xs[idplot], rev(plot_xs[idplot])),
            c(plot_quantiles[3,idplot], rev(plot_quantiles[7,idplot])),
            col = ifelse(n%in%observed_flags, util$c_mid, 'grey70'), border = NA)
    polygon(c(plot_xs[idplot], rev(plot_xs[idplot])),
            c(plot_quantiles[4,idplot], rev(plot_quantiles[6,idplot])),
            col = ifelse(n%in%observed_flags, util$c_mid_highlight, 'grey60'), border = NA)
    
    lines(plot_xs[idplot], plot_quantiles[5, idplot],
          col= ifelse(n%in%observed_flags,util$c_dark, 'grey50'), lwd=2)
  }
  
  for(i in observed_idxs_tree) {
    lines(c(years[i] - 0.5, years[i] + 0.5),
          rep(seed_counts[i], 2),
          col="white", lwd=4)
    lines(c(years[i] - 0.5, years[i] + 0.5),
          rep(data$seed_counts[i], 2),
          col="black", lwd=2)
  }
  
}
```

## Posterior inference

```{r}
par(mfrow=c(2, 5))

util$plot_expectand_pushforward(samples[['lambda1']], 25,
                                display_name="lambda1")

util$plot_expectand_pushforward(samples[['psi1']], 25,
                                display_name="psi1")

util$plot_expectand_pushforward(samples[['theta1']], 25,
                                display_name="theta1")

util$plot_expectand_pushforward(samples[['lambda20']], 25,
                                display_name="lambda20")

util$plot_expectand_pushforward(samples[['beta_lambda2_frost']], 25,
                                display_name="beta_lambda2_frost")

util$plot_expectand_pushforward(samples[['beta_lambda2_spring']], 25,
                                display_name="beta_lambda2_spring")

util$plot_expectand_pushforward(samples[['psi2']], 25,
                                display_name="psi2")


util$plot_expectand_pushforward(samples[['rho0']], 
                                24, flim=c(0, 1.1),
                                display_name="rho0",)


util$plot_expectand_pushforward(samples[['tau_nm_m0']], 
                                25, flim=c(0, 1),
                                display_name="tau_nm_m0",)

util$plot_expectand_pushforward(samples[['beta_nm_m']], 25,
                                display_name="beta_nm_m")

util$plot_expectand_pushforward(samples[['tau_m_m0']], 
                                25, flim=c(0, 1),
                                display_name="tau_m_m0")
```

